name: BuddyPocket
options:
  bundleIdPrefix: com.rezaimia
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: 1
    DEVELOPMENT_TEAM: J875R59LND
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "10.20.0"

targets:
  BuddyPocket:
    type: application
    platform: iOS
    sources:
      - BuddyPocket
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rezaimia.BuddyPocket
        INFOPLIST_FILE: BuddyPocket/Supporting/Info.plist
        CODE_SIGN_ENTITLEMENTS: BuddyPocket/Supporting/BuddyPocket.entitlements
        PROVISIONING_PROFILE_SPECIFIER: ""
        CODE_SIGN_IDENTITY: ""
    dependencies:
      - target: BuddyPocketWidget
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseDatabase
      - package: Firebase
        product: FirebaseMessaging

  BuddyPocketWidget:
    type: app-extension
    platform: iOS
    sources:
      - BuddyPocketWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rezaimia.BuddyPocketWidget
        INFOPLIST_FILE: BuddyPocketWidget/Info.plist
        CODE_SIGN_ENTITLEMENTS: BuddyPocketWidget/BuddyPocketWidget.entitlements
        PROVISIONING_PROFILE_SPECIFIER: ""
        CODE_SIGN_IDENTITY: ""
